# Site settings
title: AIML Tutorial  # Replace with your site's title
description: Learn AI ML  # Short description
author: Prashant Tyagi  # Your name or organization name
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aimltutorial.github.io"  # Your GitHub Pages URL (without the repo name)
github_username: aimltutorial  # Replace with your GitHub username

# Build settings
theme: jekyll-theme-minimal # Replace with your chosen Jekyll theme (e.g., "jekyll-theme-cayman")
plugins:
  - jekyll-feed  # Optional: Generates an RSS feed for your blog

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Markdown processor
markdown: kramdown

# Optional features
# google_analytics: UA-XXXXXX-X  # Add your Google Analytics ID (remove the comment)

# Additional configuration for your specific theme or plugins
# (Refer to their documentation for details)
